"""
Test Generator - post-processes LLM output to ensure complete JUnit 5 test coverage.
If the LLM omitted tests for a service file, this module generates stubs.
"""
import re
import logging
from typing import List

from .converter import JavaFile

logger = logging.getLogger(__name__)

_JUNIT5_TEMPLATE = """\
package {package};

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {class_name}.
 * Auto-generated by the Migration Agent - add assertions to match business logic.
 */
@ExtendWith(MockitoExtension.class)
class {class_name}Test {{

    @InjectMocks
    private {class_name} subject;

    // TODO: Add @Mock fields for dependencies

    @Test
    void contextLoads() {{
        assertThat(subject).isNotNull();
    }}

    // TODO: Add detailed test cases for each public method
}}
"""

_INTEGRATION_TEST_TEMPLATE = """\
package {package};

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Integration tests for {class_name}.
 * Auto-generated by the Migration Agent.
 */
@SpringBootTest
@AutoConfigureMockMvc
class {class_name}IT {{

    @Autowired
    private MockMvc mockMvc;

    @Test
    void healthCheck() throws Exception {{
        // TODO: replace with actual endpoint paths
        mockMvc.perform(get("/actuator/health"))
               .andExpect(status().isOk());
    }}
}}
"""


def _extract_package(content: str) -> str:
    match = re.search(r"^package\s+([\w.]+);", content, re.MULTILINE)
    return match.group(1) if match else "com.example.app"


def _extract_class_name(content: str) -> str:
    match = re.search(r"(?:public\s+)?(?:class|interface|record)\s+(\w+)", content)
    return match.group(1) if match else "UnknownClass"


def _is_service_file(java_file: JavaFile) -> bool:
    return "service" in java_file.filename.lower() and not java_file.filename.endswith("Test.java")


def _is_controller_file(java_file: JavaFile) -> bool:
    return "controller" in java_file.filename.lower() and not java_file.filename.endswith("Test.java")


def _test_filename_for(java_file: JavaFile) -> str:
    return java_file.filename.replace(
        "src/main/java", "src/test/java"
    ).replace(".java", "Test.java")


def augment_tests(
    java_files: List[JavaFile],
    test_files: List[JavaFile],
) -> List[JavaFile]:
    """
    Checks if every service / controller has a corresponding test file.
    Generates stubs for any that are missing.
    Returns the (potentially augmented) test_files list.
    """
    existing_test_names = {tf.filename for tf in test_files}
    augmented = list(test_files)

    for jf in java_files:
        expected_test = _test_filename_for(jf)
        if expected_test in existing_test_names:
            continue  # Already has a test

        if _is_service_file(jf):
            package = _extract_package(jf.content)
            class_name = _extract_class_name(jf.content)
            logger.info("Generating test stub for service: %s", class_name)
            stub = _JUNIT5_TEMPLATE.format(package=package, class_name=class_name)
            augmented.append(JavaFile(filename=expected_test, content=stub))

        elif _is_controller_file(jf):
            package = _extract_package(jf.content)
            class_name = _extract_class_name(jf.content)
            it_filename = jf.filename.replace(
                "src/main/java", "src/test/java"
            ).replace(".java", "IT.java")
            if it_filename not in existing_test_names:
                logger.info("Generating integration test stub for controller: %s", class_name)
                stub = _INTEGRATION_TEST_TEMPLATE.format(
                    package=package, class_name=class_name
                )
                augmented.append(JavaFile(filename=it_filename, content=stub))

    return augmented
